language: node_js
node_js:
  - 10.16

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g grunt-cli
  - npm install

script:
  - grunt

after_success: |
  curl
  --request POST
  -H "Accept: application/json"
  --data '{"state":"success", "target_url":"${TRAVIS_BUILD_WEB_URL}", "description":"The build succeeded!", "context":"continuous-integration/travis"}'
  https://api.github.com/repos/jamcoupe/karma-commonjs/statuses/${TRAVIS_COMMIT}
